[package]
name = "languify-server"
version = "0.1.0"
authors = ["Martin Disch <martindisch@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
serde = "1.0.127"
actix-cors = "0.5.4"
log = "0.4.14"
env_logger = "0.9.0"
